### ISSUE TITLE
Please Fix Sprig Compatibility with Semver!

### ISSUE THREAD

**Issue by eparziale** [Masterminds/sprig#176] opened 2019-08-29 21:45 UTC
@mattfarina  Can you please update sprig to be compatible with the latest Masterminds/semver changes here: https://github.com/Masterminds/semver/pull/105?

Running **go get -u github.com/Masterminds/sprig** now returns the following error:

 github.com/Masterminds/sprig
..\..\..\github.com\Masterminds\sprig\semver.go:22:2: cannot use semver.Version as type *semver.Version in return argument

semver.Version now needs to be a non-pointer, and semver_test.go needs to be updated to play nicely with this data type change.

We have golang applications that haven't migrated to go-modules yet, and that use sprig as a dependency. Can you please fix this compilation error so that our own downstream builds will succeed?

Thanks!

Eric

**Comment by djvt** [comment] 2019-08-29 22:57
this is a major issue for us as well.  please fix.

**Comment by arslantopcu1** [comment] 2019-08-30 08:30
this is a major issue for us as well. please fix.

**Comment by samuelfvlcastro** [comment] 2019-08-30 08:38
this is a major issue for us as well. please fix.

**Comment by igorsousa-b** [comment] 2019-08-30 08:39
This issue has impacted us as well. Please fix it.

**Comment by danielfoliveira** [comment] 2019-08-30 08:40
This issue broke our project also. Please fix it.

**Comment by psimoesSsimoes** [comment] 2019-08-30 08:41
This issue has impacted us as well. It would be really awesome if you could fix it.

**Comment by DianaPinheiro** [comment] 2019-08-30 08:43
his issue has impacted us as well.. It would be great if you could fix it, please!

**Comment by brunofpereira** [comment] 2019-08-30 08:47
This issue has impacted us as well. Please fix it asap

**Comment by sgkiokas** [comment] 2019-08-30 08:55
This is a major problem for us well. Thanks for the effort you will put in fixing that in advance :)

**Comment by eparziale** [comment] 2019-08-30 18:26
Masterminds owners - (https://github.com/orgs/Masterminds/people)
@mattfarina 
@technosophos 
@sdboyer 
@goetas
@franciscocpg

Can one of you please fix this sprig issue? This is impacting multiple downstream projects. (i.e. breaking continuous integration builds and preventing deploys)

Thanks!

**Comment by technosophos** [comment] 2019-08-30 22:34
Is this some weird trolling joke? One simple issue would have been sufficient. Closing as duplicate of #178

**Closed by technosophos** 2019-08-30 22:34 UTC

**Comment by mattfarina** [comment] 2019-09-03 13:59
This seems like it should really result in an issue of "please fix go get"

semver has releases using semantic versioning. v3.0.0 is in the works but `go get` pulls from the tip of master in most cases. That means it's not respecting the releases. So, when dev work for v3 changed a Go API some applications broke when installed with `go get`.

The problem isn't with semver or sprig. Does any other ecosystem default to installing application dependencies on the tip of master? I can't think of one and there's a reason for that.

**Comment by eparziale** [comment] 2019-09-03 16:07
Thanks Matt. 

Yes your summary is correct. **Go gets** reliance on the tip of master means that this issue can happen at any time (To teams not using a proper Go dependency mgmt tool)

The correct way to solve is for each application team to use some kind of Golang dependency management tool (Like Glide, dep, go modules, etc). 

Over the weekend, we adjusted our application to use dep. This solved the problem, and will prevent  similiar issues from arising for us in the future.

Thank you
